// AUTO-GENERATED by `npm run generate`. Do not edit by hand.
// Maps product/category ids to generated image paths under /public.
export const generatedImages: Record<string, string> = {};
export const generatedHero: { image: string; video: string } = { image: "", video: "" };
