// AUTO-GENERATED by `npm run generate`. Do not edit by hand.
export const generatedImages: Record<string, string> = {
  "hero": "/generated/hero.png",
  "cat-oil": "/generated/cat-oil.png",
  "cat-masala": "/generated/cat-masala.png",
  "cat-sweet": "/generated/cat-sweet.png",
  "coconut-oil": "/generated/coconut-oil.png",
  "groundnut-oil": "/generated/groundnut-oil.png",
  "gingelly-oil": "/generated/gingelly-oil.png",
  "hair-oil": "/generated/hair-oil.png",
  "neem-oil": "/generated/neem-oil.png",
  "turmeric": "/generated/turmeric.png",
  "chilli": "/generated/chilli.png",
  "coriander": "/generated/coriander.png",
  "sambar": "/generated/sambar.png",
  "garam": "/generated/garam.png",
  "curry-masala": "/generated/curry-masala.png",
  "idli-podi": "/generated/idli-podi.png",
  "nattu-vellam": "/generated/nattu-vellam.png",
  "nattu-sakkarai": "/generated/nattu-sakkarai.png"
};
export const generatedHero: { image: string; video: string } = {
  "image": "/generated/hero.png",
  "video": ""
};
